name: Build Kernel C40

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y git bc bison build-essential libssl-dev libncurses-dev flex python3 gcc-aarch64-linux-gnu

      - name: Compilar Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # Limpeza total na raiz
          make mrproper
          rm -rf out/
          mkdir -p out/
          
          # Configuração manual forçada para evitar o erro de 'Target not found'
          # Tente usar o frost_defconfig, se não existir, tente o gki_defconfig
          if [ -f arch/arm64/configs/frost_defconfig ]; then
            make O=out ARCH=arm64 frost_defconfig
          else
            make O=out ARCH=arm64 gki_defconfig
          fi
          
          # Compilação
          make O=out ARCH=arm64 V=1 KBUILD_WERROR=0 -j2

      - name: Upload Kernel Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Poco-C40
          path: out/arch/arm64/boot/Image.gz-dtb
